"""add expense models

Revision ID: 924f3aab4ff1
Revises: 7cbfa41e1c12
Create Date: 2026-07-10 23:50:44.843506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924f3aab4ff1'
down_revision: Union[str, Sequence[str], None] = '7cbfa41e1c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_share', sa.Column('amount_owed', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index(op.f('ix_expense_share_amount_owned'), table_name='expense_share')
    op.create_index(op.f('ix_expense_share_amount_owed'), 'expense_share', ['amount_owed'], unique=False)
    op.drop_column('expense_share', 'amount_owned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_share', sa.Column('amount_owned', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_expense_share_amount_owed'), table_name='expense_share')
    op.create_index(op.f('ix_expense_share_amount_owned'), 'expense_share', ['amount_owned'], unique=False)
    op.drop_column('expense_share', 'amount_owed')
    # ### end Alembic commands ###
