"""add memory for tokens

Revision ID: c2906beaf202
Revises: 924f3aab4ff1
Create Date: 2026-08-17 21:05:35.586511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2906beaf202'
down_revision: Union[str, Sequence[str], None] = '924f3aab4ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('acces_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_acces_token'), 'user', ['acces_token'], unique=False)
    op.create_index(op.f('ix_user_refresh_token'), 'user', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refresh_token'), table_name='user')
    op.drop_index(op.f('ix_user_acces_token'), table_name='user')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'acces_token')
    # ### end Alembic commands ###
