"""add tokens

Revision ID: e0d87931d986
Revises: c2906beaf202
Create Date: 2026-08-17 21:11:58.790718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d87931d986'
down_revision: Union[str, Sequence[str], None] = 'c2906beaf202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_acces_token'), table_name='user')
    op.drop_index(op.f('ix_user_refresh_token'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_refresh_token'), 'user', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_user_acces_token'), 'user', ['acces_token'], unique=False)
    # ### end Alembic commands ###
